spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  jwt:
    secret_key: ${SECRET_KEY}
    access_exp: ${ACCESS_EXP}
    refresh_exp: ${REFRESH_EXP}
    header: ${HEADER}
    prefix: ${PREFIX}

redis:
  host: ${REDIS_HOST:localhost}
  port: 6379

server:
  port: 8080